/**
 * 義憤（righteous indignation / outrage）検出用の手作り辞書。
 *
 * 形式: [ 表層形, 重み, カテゴリ, フラグ ]
 *   フラグ 'noNeg' : 直後に否定語尾（〜ない/〜ではない）が来ても減衰させない
 *                    （「許さない」「あり得ない」自体が強い義憤表現のため）
 *
 * 重みの目安: 1.0 弱い / 1.6 明確 / 2.2 強い罵倒 / 3.0 最強（殺害・差別スラング等）
 * カテゴリ: attack / hostility / incitement / absolute / othering / cynicism / urgency
 *
 * 部分一致の誤検知対策は lexicon.js の EXCLUDE_AFTER を参照。
 */
(function (root, factory) {
  'use strict';
  var api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else (root.JOF = root.JOF || {}).lexiconCurated = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  return [
    // ---- attack: 攻撃・侮蔑 ----
    ['死ね', 3.2, 'attack'],
    ['氏ね', 3.2, 'attack'],
    ['殺す', 2.8, 'attack'],
    ['殺せ', 3.0, 'attack'],
    ['殺害しろ', 3.0, 'attack'],
    ['消えろ', 2.6, 'attack'],
    ['消え失せろ', 3.0, 'attack'],
    ['失せろ', 2.6, 'attack'],
    ['失せな', 2.2, 'attack'],
    ['いなくなれ', 2.2, 'attack'],
    ['どっか行け', 2.2, 'attack'],
    ['クズ', 2.4, 'attack'],
    ['ゴミ', 2.0, 'attack'],
    ['カス', 2.2, 'attack'],
    ['バカ', 1.6, 'attack'],
    ['馬鹿', 1.6, 'attack'],
    ['アホ', 1.5, 'attack'],
    ['間抜け', 1.5, 'attack'],
    ['まぬけ', 1.4, 'attack'],
    ['無能', 1.8, 'attack'],
    ['役立たず', 1.8, 'attack'],
    ['害悪', 2.0, 'attack'],
    ['害虫', 2.2, 'attack'],
    ['ウジ虫', 2.6, 'attack'],
    ['クソ', 2.0, 'attack'],
    ['くそ野郎', 2.6, 'attack'],
    ['野郎', 1.2, 'attack'],
    ['てめえ', 1.6, 'attack'],
    ['てめぇ', 1.6, 'attack'],
    ['貴様', 2.0, 'attack'],
    ['きさま', 1.8, 'attack'],
    ['お前ら', 0.8, 'attack'],
    ['おまえら', 0.8, 'attack'],
    ['キチガイ', 2.8, 'attack'],
    ['基地外', 2.6, 'attack'],
    ['低能', 2.4, 'attack'],
    ['ボンクラ', 1.8, 'attack'],
    ['ポンコツ', 1.5, 'attack'],
    ['マヌケ', 1.6, 'attack'],
    ['老害', 2.2, 'attack'],
    ['負け犬', 1.8, 'attack'],
    ['雑魚', 1.8, 'attack'],
    ['カス共', 2.6, 'attack'],
    ['ボケ', 0.8, 'attack'],
    ['クソ野郎', 2.8, 'attack'],
    ['カス野郎', 2.8, 'attack'],
    ['バカ野郎', 2.4, 'attack'],
    ['ゴミ野郎', 2.6, 'attack'],
    ['税金泥棒', 2.0, 'attack'],
    ['詐欺師', 1.6, 'attack'],
    ['嘘つき', 1.3, 'attack'],
    ['ホラ吹き', 1.5, 'attack'],
    ['ペテン師', 1.8, 'attack'],
    ['エセ', 1.2, 'attack'],
    ['頭おかしい', 2.0, 'attack'],
    ['頭がおかしい', 2.0, 'attack'],
    ['正気か', 1.4, 'attack'],
    ['狂ってる', 1.8, 'attack'],
    ['狂人', 2.2, 'attack'],
    ['異常者', 2.2, 'attack'],
    ['変態', 1.6, 'attack'],
    ['クソ人間', 2.8, 'attack'],
    ['人間のクズ', 3.0, 'attack'],
    ['社会のゴミ', 2.8, 'attack'],
    ['死んだほうが', 3.0, 'attack'],
    ['死んだ方が', 3.0, 'attack'],
    ['ゴミカス', 2.6, 'attack'],
    ['クズカス', 2.6, 'attack'],
    ['カスゴミ', 2.6, 'attack'],

    // ---- hostility: 憎悪・敵意 ----
    ['許せない', 2.0, 'hostility', 'noNeg'],
    ['許さない', 1.8, 'hostility', 'noNeg'],
    ['絶対に許さない', 2.6, 'hostility', 'noNeg'],
    ['絶対許さない', 2.6, 'hostility', 'noNeg'],
    ['許しがたい', 2.2, 'hostility'],
    ['許し難い', 2.2, 'hostility'],
    ['憎い', 2.0, 'hostility'],
    ['憎む', 1.8, 'hostility'],
    ['憎しみ', 1.8, 'hostility'],
    ['大嫌い', 1.8, 'hostility'],
    ['嫌い', 0.7, 'hostility'],
    ['嫌悪', 1.6, 'hostility'],
    ['ムカつく', 1.6, 'hostility'],
    ['むかつく', 1.6, 'hostility'],
    ['腹立つ', 1.5, 'hostility'],
    ['腹が立つ', 1.6, 'hostility'],
    ['頭にくる', 1.5, 'hostility'],
    ['頭に来る', 1.5, 'hostility'],
    ['殺意', 3.0, 'hostility'],
    ['ぶっ飛ばす', 2.4, 'hostility'],
    ['ぶん殴る', 2.6, 'hostility'],
    ['殴りたい', 2.2, 'hostility'],
    ['地獄に落ちろ', 2.8, 'hostility'],
    ['死んでほしい', 2.8, 'hostility'],
    ['消えてほしい', 2.4, 'hostility'],
    ['怒り', 1.4, 'hostility'],
    ['激怒', 1.8, 'hostility'],
    ['憤慨', 1.8, 'hostility'],
    ['義憤', 1.6, 'hostility'],
    ['怒り心頭', 2.2, 'hostility'],
    ['煮えくり返る', 2.2, 'hostility'],
    ['言語道断', 2.0, 'hostility'],
    ['けしからん', 1.8, 'hostility'],
    ['不愉快', 1.4, 'hostility'],
    ['不快', 1.2, 'hostility'],
    ['胸糞', 2.2, 'hostility'],
    ['胸クソ', 2.2, 'hostility'],
    ['胸くそ', 2.2, 'hostility'],
    ['気持ち悪い', 1.4, 'hostility'],
    ['キモい', 1.8, 'hostility'],
    ['きもい', 1.6, 'hostility'],
    ['悍ましい', 2.2, 'hostility'],
    ['おぞましい', 2.0, 'hostility'],
    ['戦慄', 1.6, 'hostility'],
    ['呆れる', 1.4, 'hostility'],
    ['呆れた', 1.4, 'hostility'],
    ['あきれる', 1.4, 'hostility'],
    ['唖然', 1.4, 'hostility'],
    ['ありえない', 1.8, 'hostility', 'noNeg'],
    ['あり得ない', 1.8, 'hostility', 'noNeg'],
    ['信じられない', 1.6, 'hostility', 'noNeg'],
    ['絶望', 1.5, 'hostility'],
    ['もう終わり', 1.3, 'hostility'],
    ['終わってる', 1.3, 'hostility'],
    ['終わっている', 1.3, 'hostility'],

    // ---- incitement: 煽り・呼びかけ ----
    ['叩け', 2.0, 'incitement'],
    ['叩くべき', 1.8, 'incitement'],
    ['晒せ', 2.6, 'incitement'],
    ['晒すべき', 2.0, 'incitement'],
    ['晒し上げ', 2.2, 'incitement'],
    ['吊るせ', 2.8, 'incitement'],
    ['制裁', 1.8, 'incitement'],
    ['制裁しろ', 2.2, 'incitement'],
    ['断罪', 2.2, 'incitement'],
    ['糾弾', 2.2, 'incitement'],
    ['糾弾しろ', 2.6, 'incitement'],
    ['追い出せ', 2.2, 'incitement'],
    ['追放しろ', 2.4, 'incitement'],
    ['出て行け', 2.4, 'incitement'],
    ['出ていけ', 2.4, 'incitement'],
    ['ボイコット', 1.6, 'incitement'],
    ['不買', 1.4, 'incitement'],
    ['拡散希望', 1.2, 'incitement'],
    ['拡散しろ', 1.8, 'incitement'],
    ['声を上げろ', 1.6, 'incitement'],
    ['立ち上がれ', 1.4, 'incitement'],
    ['抗議しろ', 1.8, 'incitement'],
    ['謝罪しろ', 2.0, 'incitement'],
    ['土下座しろ', 2.2, 'incitement'],
    ['責任取れ', 2.0, 'incitement'],
    ['辞めろ', 1.8, 'incitement'],
    ['辞任しろ', 1.8, 'incitement'],
    ['降りろ', 1.6, 'incitement'],
    ['黙れ', 2.2, 'incitement'],
    ['黙ってろ', 2.4, 'incitement'],
    ['引っ込め', 2.0, 'incitement'],
    ['袋叩き', 2.4, 'incitement'],
    ['殺到しろ', 2.2, 'incitement'],
    ['突撃しろ', 2.2, 'incitement'],
    ['電凸', 1.8, 'incitement'],

    // ---- absolute: 断定・絶対化 ----
    ['絶対', 0.7, 'absolute'],
    ['絶対に', 1.0, 'absolute'],
    ['必ず', 0.4, 'absolute'],
    ['論外', 1.6, 'absolute'],
    ['完全に', 0.6, 'absolute'],
    ['二度と', 0.8, 'absolute'],
    ['確定', 0.5, 'absolute'],
    ['間違いない', 1.0, 'absolute'],
    ['明らか', 0.3, 'absolute'],
    ['100%', 0.7, 'absolute'],
    ['百パー', 0.7, 'absolute'],
    ['ありえん', 1.4, 'absolute'],
    ['あり得ん', 1.4, 'absolute'],
    ['そんなわけない', 1.2, 'absolute'],
    ['絶対ありえない', 2.0, 'absolute', 'noNeg'],

    // ---- othering: 二項対立・レッテル ----
    ['信者', 1.4, 'othering'],
    ['工作員', 2.0, 'othering'],
    ['ネトウヨ', 2.2, 'othering'],
    ['パヨク', 2.2, 'othering'],
    ['左翼', 1.0, 'othering'],
    ['右翼', 1.0, 'othering'],
    ['反日', 1.8, 'othering'],
    ['売国', 2.2, 'othering'],
    ['売国奴', 2.6, 'othering'],
    ['非国民', 2.4, 'othering'],
    ['国賊', 2.4, 'othering'],
    ['分際', 2.0, 'othering'],
    ['ごとき', 1.2, 'othering'],
    ['如き', 1.2, 'othering'],
    ['自称', 0.8, 'othering'],
    ['どこぞの', 1.2, 'othering'],
    ['カルト', 1.2, 'othering'],
    ['洗脳', 1.6, 'othering'],
    ['マインドコントロール', 1.4, 'othering'],
    ['手先', 1.2, 'othering'],
    ['犬コロ', 1.4, 'othering'],
    ['傀儡', 1.6, 'othering'],
    ['外敵', 1.4, 'othering'],
    ['敵国', 1.6, 'othering'],
    ['スパイ', 1.4, 'othering'],

    // ---- cynicism: 冷笑・皮肉 ----
    ['どうせ', 1.0, 'cynicism'],
    ['はいはい', 1.2, 'cynicism'],
    ['だから何', 1.4, 'cynicism'],
    ['知らんがな', 1.4, 'cynicism'],
    ['知らんけど', 0.8, 'cynicism'],
    ['草', 0.5, 'cynicism'],
    ['www', 0.8, 'cynicism'],
    ['笑笑', 1.2, 'cynicism'],
    ['ざまあ', 1.8, 'cynicism'],
    ['ざまあみろ', 2.2, 'cynicism'],
    ['いい気味', 2.0, 'cynicism'],
    ['自業自得', 1.4, 'cynicism'],
    ['知ったか', 1.2, 'cynicism'],
    ['ドヤ顔', 1.0, 'cynicism'],
    ['マウント', 1.0, 'cynicism'],

    // ---- urgency: 危機煽り ----
    ['緊急', 1.0, 'urgency'],
    ['今すぐ', 0.8, 'urgency'],
    ['危険', 0.8, 'urgency'],
    ['終わりの始まり', 1.8, 'urgency'],
    ['日本が終わる', 2.0, 'urgency'],
    ['日本終了', 2.0, 'urgency'],
    ['日本終わった', 2.0, 'urgency'],
    ['滅びる', 1.6, 'urgency'],
    ['崩壊', 1.2, 'urgency'],
    ['破滅', 1.6, 'urgency'],
    ['滅亡', 1.6, 'urgency'],
    ['亡国', 1.8, 'urgency'],
    ['取り返しのつかない', 1.8, 'urgency'],
    ['とんでもない', 1.0, 'urgency'],
    ['前代未聞', 1.4, 'urgency'],
    ['史上最悪', 1.8, 'urgency'],
    ['最悪', 1.0, 'urgency'],
    ['最悪だ', 1.4, 'urgency'],
    ['ひどい', 0.8, 'urgency'],
    ['酷い', 0.8, 'urgency'],
    ['酷すぎる', 1.6, 'urgency'],
    ['大問題', 1.0, 'urgency'],
    ['深刻', 0.8, 'urgency'],
    ['危機', 1.0, 'urgency'],
    ['警鐘', 1.0, 'urgency'],
    ['このままでは', 0.8, 'urgency'],
    ['滅び', 1.4, 'urgency']
  ];
});
